name: run main.py

on:
  schedule:
    - cron: '0 * * * *' # Every 1 hr

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v4.1.1 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.10.7' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run main.py
        run: 
            python scrape.py
          
      - name: commit files
        run: |
          git config --local user.email "bimaldhital@gmail.com"
          git config --local user.name "833M0L3"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "scraped notices" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 